// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebooztrztxcbsthnqvme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVib296dHJ6dHhjYnN0aG5xdm1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDE3MDgsImV4cCI6MjA2NTU3NzcwOH0.dH-aEe42hEWvEz98qgtn_2CWKhMiiCpdoEJaYvd3lM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);